<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>REST</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>9d42a61b-4773-4924-8598-e4b9e8ce3d2b</testSuiteGuid>
   <testCaseLink>
      <guid>7d4225d5-12c6-430c-81fa-88c1e1bbf599</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/REST/ATC-05 - Add a Pet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83b70a17-136e-4c31-ae9b-2c01a1a38755</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9b63ed8-3d29-4628-a9ee-d4fc9c4d3386</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20dc9116-584d-4b71-93b4-de9f2ba976f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/REST/ATC-06 - Get a Pet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9e978e7-3f53-4050-9e7a-45045bd38f37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85b55477-4863-4d1a-a594-3b037137e762</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09fbc0bf-a986-49e2-968a-057065f5f0bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9bd6eeb4-0016-4b24-8c24-90f75df00902</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/REST/ATC-07 - Delete a Pet</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd8593d8-c455-4a4c-8d58-4632adaa6e7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>891d8e45-7366-4e5a-86e1-8b5974684833</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1029ab9-55aa-4ed7-a2be-e6557a5c01b5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
