<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SOAP</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2a931f4d-02a0-4b4d-9bf1-78d84f231dcd</testSuiteGuid>
   <testCaseLink>
      <guid>83e4f609-a63d-4232-900e-1c56f6e3ccdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOAP/ATC-01 - Verify Add Calculator</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>695db671-fa4d-4acc-843f-e904d5d2f880</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bbf799c-e45a-476d-a87d-4865853e2a65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2eeb3a8-b659-4d3c-ac01-fcf5fa4ef067</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38de10b0-cefd-47cc-835c-9be747c1ffe7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70d38286-47a3-4909-a895-1143e89ac53c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOAP/ATC-02 - Verify Divide Calculator</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>143bd445-67d9-47b0-83f0-8292aad12179</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1a16056-27ef-45bf-9d9a-c72adf658cf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb6605be-b7ad-4baf-bb1c-579cd2f053f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c627269-a2ee-412a-aefd-61fb2053064e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84cdb593-d677-47c8-b67f-fe48638d0a4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOAP/ATC-03 - Verify Multiply Calculator</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ed06d77-7e1c-409c-a502-7e1f4b31b30c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a10a6b5-df39-4562-883b-02ed534467cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c44b2f37-04b0-41b9-b9fe-b20f3b27a1c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e483eaf-997c-4f66-ad3e-48a86fdf89a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f46fa5d7-2a9f-4319-b2c5-954519f1e597</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SOAP/ATC-04 - Verify Subtract Calculator</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2df75fa2-89d5-4cdb-998f-0a4f7e643313</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16a4446f-3636-4bb5-8459-ea45d92bd963</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c93e434-58ee-47bc-8b55-03bf51e84ed5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>849db67e-26ff-444f-a269-8d51118a050e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
